import 'package:flutter/material.dart';

/// CapCut-class feature set: 135 CapCut tools + #136 AI Kurdish subtitles.
enum FeatureCategory {
  montage,
  audio,
  text,
  effects,
  stickers,
  ai,
  templates,
  export,
  captions,
}

enum FeatureStatus {
  /// Wired and usable in this app.
  ready,
  /// Partial / preview controls exist.
  partial,
  /// Listed for roadmap; UI entry only.
  planned,
}

class AppFeature {
  const AppFeature({
    required this.id,
    required this.number,
    required this.titleKu,
    required this.titleEn,
    required this.category,
    required this.icon,
    required this.status,
    this.actionId,
  });

  final String id;
  final int number;
  final String titleKu;
  final String titleEn;
  final FeatureCategory category;
  final IconData icon;
  final FeatureStatus status;

  /// Maps to [FeatureActions] handler key.
  final String? actionId;
}

class FeatureCatalog {
  FeatureCatalog._();

  static const total = 136;

  static String categoryLabel(FeatureCategory c) => switch (c) {
        FeatureCategory.montage => 'مۆنتاژ',
        FeatureCategory.audio => 'دەنگ',
        FeatureCategory.text => 'نووسین',
        FeatureCategory.effects => 'ئێفێکت',
        FeatureCategory.stickers => 'ستیکەر',
        FeatureCategory.ai => 'AI',
        FeatureCategory.templates => 'تێمپلەیت',
        FeatureCategory.export => 'ئێکسپۆرت',
        FeatureCategory.captions => 'ژێرنووس',
      };

  static List<AppFeature> all() => _all;

  static List<AppFeature> byCategory(FeatureCategory c) =>
      _all.where((f) => f.category == c).toList();

  static List<AppFeature> search(String q) {
    final s = q.trim().toLowerCase();
    if (s.isEmpty) return _all;
    return _all
        .where(
          (f) =>
              f.titleEn.toLowerCase().contains(s) ||
              f.titleKu.contains(q.trim()) ||
              '${f.number}'.contains(s) ||
              f.id.contains(s),
        )
        .toList();
  }

  static AppFeature? byId(String id) {
    for (final f in _all) {
      if (f.id == id) return f;
    }
    return null;
  }

  static final List<AppFeature> _all = [
    // A. Montage 1–20
    _f(1, 'multi_track', 'تایمڵاینی فرە-تراک', 'Multi-track timeline',
        FeatureCategory.montage, Icons.view_timeline_outlined, FeatureStatus.ready,
        'open_timeline'),
    _f(2, 'import_media', 'هاوردەی ڤیدیۆ/وێنە/دەنگ', 'Import video / image / audio',
        FeatureCategory.montage, Icons.file_upload_outlined, FeatureStatus.ready,
        'import_media'),
    _f(3, 'trim_split', 'بڕین / Splite', 'Trim / Cut / Split',
        FeatureCategory.montage, Icons.call_split, FeatureStatus.ready, 'split_clip'),
    _f(4, 'delete_dup', 'سڕینەوە / دووبارەکردنەوە', 'Delete / Duplicate clip',
        FeatureCategory.montage, Icons.content_copy, FeatureStatus.ready,
        'duplicate_clip'),
    _f(5, 'ripple_delete', 'Ripple delete', 'Ripple delete',
        FeatureCategory.montage, Icons.delete_sweep_outlined, FeatureStatus.ready,
        'ripple_delete'),
    _f(6, 'reverse', 'پێچەوانەکردنی ڤیدیۆ', 'Reverse video',
        FeatureCategory.montage, Icons.replay, FeatureStatus.ready, 'reverse_clip'),
    _f(7, 'speed', 'خێرایی (خاو/خێرا)', 'Speed slow / fast / curve',
        FeatureCategory.montage, Icons.speed, FeatureStatus.ready, 'speed_clip'),
    _f(8, 'freeze', 'Freeze frame', 'Freeze frame',
        FeatureCategory.montage, Icons.pause_circle_outline, FeatureStatus.ready,
        'freeze_frame'),
    _f(9, 'crop_zoom', 'Crop / Zoom / Pan', 'Crop / Zoom / Pan',
        FeatureCategory.montage, Icons.crop, FeatureStatus.ready, 'crop_clip'),
    _f(10, 'rotate_flip', 'سوڕان / هەڵگەڕان', 'Rotate / Flip',
        FeatureCategory.montage, Icons.rotate_90_degrees_ccw, FeatureStatus.ready,
        'rotate_flip'),
    _f(11, 'aspect', 'ڕێژەی شاشە', 'Aspect ratio',
        FeatureCategory.montage, Icons.aspect_ratio, FeatureStatus.ready,
        'aspect_ratio'),
    _f(12, 'canvas', 'پاشبنەمای کانڤاس', 'Canvas / background color',
        FeatureCategory.montage, Icons.palette_outlined, FeatureStatus.ready,
        'canvas_color'),
    _f(13, 'replace', 'گۆڕینی کلیپ', 'Replace clip',
        FeatureCategory.montage, Icons.swap_horiz, FeatureStatus.ready,
        'replace_clip'),
    _f(14, 'merge', 'یەکخستنی کلیپ', 'Merge / compound clip',
        FeatureCategory.montage, Icons.merge_type, FeatureStatus.ready,
        'merge_clips'),
    _f(15, 'keyframes', 'Keyframe animation', 'Keyframe animation',
        FeatureCategory.montage, Icons.timeline, FeatureStatus.ready,
        'keyframes'),
    _f(16, 'opacity', 'Opacity / blend', 'Opacity / blend',
        FeatureCategory.montage, Icons.opacity, FeatureStatus.ready, 'opacity'),
    _f(17, 'clip_volume', 'دەنگی هەر کلیپێک', 'Volume per clip',
        FeatureCategory.montage, Icons.volume_up_outlined, FeatureStatus.ready,
        'clip_volume'),
    _f(18, 'fade', 'Fade in / out', 'Fade in / out',
        FeatureCategory.montage, Icons.gradient, FeatureStatus.ready, 'fade'),
    _f(19, 'snap', 'Snap to playhead', 'Snap to beat / playhead',
        FeatureCategory.montage, Icons.vertical_align_center, FeatureStatus.ready,
        'snap'),
    _f(20, 'undo_redo', 'Undo / Redo', 'Undo / Redo history',
        FeatureCategory.montage, Icons.history, FeatureStatus.ready, 'undo_redo'),

    // B. Audio 21–35
    _f(21, 'music_lib', 'کتێبخانەی میوزیک', 'Music library',
        FeatureCategory.audio, Icons.library_music_outlined, FeatureStatus.ready,
        'open_audio'),
    _f(22, 'sfx_lib', 'دەنگی ئێفێکت', 'Sound effects library',
        FeatureCategory.audio, Icons.surround_sound_outlined, FeatureStatus.ready,
        'open_audio'),
    _f(23, 'extract_audio', 'دەرهێنانی دەنگ لە ڤیدیۆ', 'Extract audio from video',
        FeatureCategory.audio, Icons.audio_file_outlined, FeatureStatus.ready,
        'extract_audio'),
    _f(24, 'voiceover', 'تۆماری دەنگ', 'Voiceover recording',
        FeatureCategory.audio, Icons.mic_none, FeatureStatus.ready, 'open_audio'),
    _f(25, 'beat_sync', 'هاوکاتکردن لەگەڵ بیت', 'Auto beat sync',
        FeatureCategory.audio, Icons.graphic_eq, FeatureStatus.ready, 'open_audio'),
    _f(26, 'voice_fx', 'ئێفێکتی دەنگ', 'Voice effects',
        FeatureCategory.audio, Icons.record_voice_over, FeatureStatus.ready,
        'open_audio'),
    _f(27, 'noise_reduce', 'کەمکردنەوەی ژاوەژاو', 'Noise reduction',
        FeatureCategory.audio, Icons.hearing_disabled, FeatureStatus.ready,
        'open_audio'),
    _f(28, 'voice_enhance', 'باشترکردنی دەنگ', 'Voice enhancement',
        FeatureCategory.audio, Icons.tune, FeatureStatus.ready, 'open_audio'),
    _f(29, 'auto_volume', 'دەنگی ئۆتۆماتیکی', 'Auto volume / loudness',
        FeatureCategory.audio, Icons.equalizer, FeatureStatus.ready, 'open_audio'),
    _f(30, 'ducking', 'Ducking', 'Ducking music under voice',
        FeatureCategory.audio, Icons.music_off, FeatureStatus.ready, 'open_audio'),
    _f(31, 'audio_stretch', 'درێژکردنەوەی دەنگ', 'Audio stretch',
        FeatureCategory.audio, Icons.straighten, FeatureStatus.ready, 'open_audio'),
    _f(32, 'multi_audio', 'فرە-تراکی دەنگ', 'Multi audio tracks',
        FeatureCategory.audio, Icons.queue_music, FeatureStatus.ready, 'open_audio'),
    _f(33, 'mute_solo', 'Mute / Solo', 'Mute / Solo',
        FeatureCategory.audio, Icons.volume_off_outlined, FeatureStatus.ready,
        'mute_original'),
    _f(34, 'audio_fade', 'Fadeی دەنگ', 'Audio fade handles',
        FeatureCategory.audio, Icons.linear_scale, FeatureStatus.ready, 'open_audio'),
    _f(35, 'import_audio', 'هاوردەی MP3/M4A/WAV', 'Import MP3/M4A/WAV',
        FeatureCategory.audio, Icons.audiotrack, FeatureStatus.ready, 'open_audio'),

    // C. Text & Captions 36–55
    _f(36, 'auto_captions', 'ژێرنووسی ئۆتۆماتیکی AI', 'Auto Captions AI',
        FeatureCategory.text, Icons.closed_caption, FeatureStatus.ready,
        'open_text'),
    _f(37, 'multi_lang_asr', 'ناساندنی فرە-زمان', 'Multi-language speech recognition',
        FeatureCategory.text, Icons.translate, FeatureStatus.ready, 'open_text'),
    _f(38, 'caption_list', 'لیستی دەستکاری ژێرنووس', 'Caption edit list',
        FeatureCategory.text, Icons.list_alt, FeatureStatus.ready, 'open_text'),
    _f(39, 'karaoke', 'Karaoke / وشە-بە-وشە', 'Karaoke word highlight',
        FeatureCategory.text, Icons.lyrics_outlined, FeatureStatus.ready,
        'open_animation'),
    _f(40, 'caption_templates', 'تێمپلەیتی ژێرنووس', 'Caption templates',
        FeatureCategory.text, Icons.style, FeatureStatus.ready, 'open_style'),
    _f(41, 'font_lib', 'کتێبخانەی فۆنت', 'Font library',
        FeatureCategory.text, Icons.font_download_outlined, FeatureStatus.ready,
        'open_style'),
    _f(42, 'text_color', 'ڕەنگ / outline / سێبەر', 'Text color / outline / shadow',
        FeatureCategory.text, Icons.format_color_text, FeatureStatus.ready,
        'open_style'),
    _f(43, 'text_anim', 'ئەنیمەیشنی نووسین', 'Text animation',
        FeatureCategory.text, Icons.animation, FeatureStatus.ready, 'open_animation'),
    _f(44, 'text_track', 'شوێنکەوتنی ئۆبجێکت', 'Text tracking',
        FeatureCategory.text, Icons.track_changes, FeatureStatus.ready,
        'open_text'),
    _f(45, 'manual_captions', 'ژێرنووسی دەستی', 'Manual captions',
        FeatureCategory.text, Icons.edit_note, FeatureStatus.ready, 'open_text'),
    _f(46, 'translate_captions', 'وەرگێڕانی ژێرنووس', 'Translate captions',
        FeatureCategory.text, Icons.g_translate, FeatureStatus.ready, 'open_text'),
    _f(47, 'auto_lyrics', 'گۆرانی / lyrics', 'Auto lyrics for songs',
        FeatureCategory.text, Icons.music_note, FeatureStatus.ready, 'open_text'),
    _f(48, 'import_srt', 'هاوردەی SRT/TXT', 'Import SRT/TXT',
        FeatureCategory.text, Icons.upload_file, FeatureStatus.ready, 'import_srt'),
    _f(49, 'export_captions', 'ئێکسپۆرتی ژێرنووس', 'Export captions',
        FeatureCategory.text, Icons.download, FeatureStatus.ready, 'open_export'),
    _f(50, 'text_bubbles', 'بۆقڵەی نووسین', 'Text bubbles / stickers text',
        FeatureCategory.text, Icons.chat_bubble_outline, FeatureStatus.ready,
        'open_stickers'),
    _f(51, 'titles', 'Title / lower-third', 'Title / lower-third presets',
        FeatureCategory.text, Icons.title, FeatureStatus.ready, 'open_style'),
    _f(52, 'neon_text', 'Glow / neon text', 'Glow / neon text',
        FeatureCategory.text, Icons.highlight, FeatureStatus.ready, 'open_style'),
    _f(53, 'stroke_box', 'Stroke / background box', 'Stroke / background box',
        FeatureCategory.text, Icons.border_color, FeatureStatus.ready, 'open_style'),
    _f(54, 'text_keyframes', 'Keyframeی نووسین', 'Text position keyframes',
        FeatureCategory.text, Icons.open_with, FeatureStatus.ready, 'open_style'),
    _f(55, 'bulk_restyle', 'گۆڕینی ستایلی هەموو', 'Bulk caption restyle',
        FeatureCategory.text, Icons.format_paint, FeatureStatus.ready, 'open_style'),

    // D. Effects 56–75
    _f(56, 'transitions', 'کتێبخانەی ترانزیشن', 'Transitions library',
        FeatureCategory.effects, Icons.swap_horiz_rounded, FeatureStatus.ready,
        'transitions'),
    _f(57, 'video_fx', 'ئێفێکتی ڤیدیۆ', 'Video effects',
        FeatureCategory.effects, Icons.blur_on, FeatureStatus.ready, 'effects'),
    _f(58, 'body_fx', 'ئێفێکتی جەستە', 'Body effects',
        FeatureCategory.effects, Icons.accessibility_new, FeatureStatus.ready,
        'effects'),
    _f(59, 'face_fx', 'ئێفێکتی دەموچاو', 'Face effects / beauty',
        FeatureCategory.effects, Icons.face_retouching_natural, FeatureStatus.ready,
        'ai_studio'),
    _f(60, 'filters', 'فلتەر / LUT', 'Filters / LUTs',
        FeatureCategory.effects, Icons.filter, FeatureStatus.ready, 'filters'),
    _f(61, 'adjust', 'Adjust ڕووناکی/کۆنتراست', 'Adjust brightness / contrast',
        FeatureCategory.effects, Icons.wb_sunny_outlined, FeatureStatus.ready,
        'adjust'),
    _f(62, 'hsl', 'HSL / color wheels', 'HSL / color wheels',
        FeatureCategory.effects, Icons.color_lens_outlined, FeatureStatus.ready,
        'adjust'),
    _f(63, 'vignette', 'Vignette / grain', 'Vignette / grain',
        FeatureCategory.effects, Icons.blur_circular, FeatureStatus.ready,
        'adjust'),
    _f(64, 'motion_track', 'Motion tracking FX', 'Motion tracking effects',
        FeatureCategory.effects, Icons.gps_fixed, FeatureStatus.ready, 'ai_studio'),
    _f(65, 'mask', 'Mask / shape mask', 'Mask / shape mask',
        FeatureCategory.effects, Icons.crop_square, FeatureStatus.ready, 'effects'),
    _f(66, 'chroma', 'Chroma key', 'Chroma key green screen',
        FeatureCategory.effects, Icons.wallpaper, FeatureStatus.ready, 'effects'),
    _f(67, 'blend', 'Blend modes', 'Blend modes',
        FeatureCategory.effects, Icons.layers, FeatureStatus.ready, 'opacity'),
    _f(68, 'overlay_fx', 'Overlay effects', 'Overlay effects',
        FeatureCategory.effects, Icons.layers_outlined, FeatureStatus.ready,
        'open_stickers'),
    _f(69, 'speed_ramp', 'Speed ramping FX', 'Speed ramping FX',
        FeatureCategory.effects, Icons.ssid_chart, FeatureStatus.ready, 'speed_clip'),
    _f(70, 'camera_fx', '3D zoom / camera FX', '3D zoom / camera FX',
        FeatureCategory.effects, Icons.threed_rotation, FeatureStatus.ready,
        'effects'),
    _f(71, 'stabilize', 'Stabilization', 'Stabilization',
        FeatureCategory.effects, Icons.videocam, FeatureStatus.ready, 'ai_studio'),
    _f(72, 'auto_enhance', 'باشترکردنی ئۆتۆ', 'Auto enhance',
        FeatureCategory.effects, Icons.auto_awesome, FeatureStatus.ready, 'adjust'),
    _f(73, 'retouch', 'Retouch / makeup AI', 'Retouch / makeup AI',
        FeatureCategory.effects, Icons.spa_outlined, FeatureStatus.ready, 'ai_studio'),
    _f(74, 'skin_smooth', 'نەرمکردنی پێست', 'Skin smooth',
        FeatureCategory.effects, Icons.face, FeatureStatus.ready, 'ai_studio'),
    _f(75, 'light_leaks', 'Flash / light leaks', 'Flash / light leaks',
        FeatureCategory.effects, Icons.flash_on, FeatureStatus.ready, 'filters'),

    // E. Stickers 76–85
    _f(76, 'sticker_lib', 'کتێبخانەی ستیکەر', 'Stickers library',
        FeatureCategory.stickers, Icons.emoji_emotions_outlined, FeatureStatus.ready,
        'open_stickers'),
    _f(77, 'anim_stickers', 'ستیکەری ئەنیمەیت', 'Animated stickers',
        FeatureCategory.stickers, Icons.gif_box_outlined, FeatureStatus.ready,
        'open_stickers'),
    _f(78, 'emoji', 'Emoji stickers', 'Emoji stickers',
        FeatureCategory.stickers, Icons.emoji_emotions, FeatureStatus.ready,
        'open_stickers'),
    _f(79, 'pip', 'Picture-in-Picture', 'Picture-in-Picture',
        FeatureCategory.stickers, Icons.picture_in_picture_alt, FeatureStatus.ready,
        'open_stickers'),
    _f(80, 'overlay_video', 'Overlay video', 'Overlay video',
        FeatureCategory.stickers, Icons.video_library_outlined, FeatureStatus.ready,
        'import_media'),
    _f(81, 'image_layer', 'لایەری وێنە', 'Image layer',
        FeatureCategory.stickers, Icons.image_outlined, FeatureStatus.ready,
        'open_stickers'),
    _f(82, 'sticker_kf', 'Keyframeی ستیکەر', 'Sticker keyframes',
        FeatureCategory.stickers, Icons.animation, FeatureStatus.ready,
        'open_stickers'),
    _f(83, 'auto_align', 'ڕێکخستنی ئۆتۆ', 'Auto align stickers',
        FeatureCategory.stickers, Icons.align_horizontal_center, FeatureStatus.ready,
        'open_stickers'),
    _f(84, 'blend_overlay', 'Blend overlays', 'Blend overlays',
        FeatureCategory.stickers, Icons.layers, FeatureStatus.ready, 'open_stickers'),
    _f(85, 'watermark', 'واتەرمارک', 'Brand watermark',
        FeatureCategory.stickers, Icons.branding_watermark, FeatureStatus.ready,
        'open_stickers'),

    // F. AI 86–115
    _f(86, 'autocut', 'AutoCut', 'AutoCut',
        FeatureCategory.ai, Icons.content_cut, FeatureStatus.ready, 'effects'),
    _f(87, 'ai_clipper', 'AI Clipper', 'AI Clipper best moments',
        FeatureCategory.ai, Icons.movie_filter, FeatureStatus.ready, 'effects'),
    _f(88, 'long_to_short', 'Long → Shorts', 'Long video to Shorts',
        FeatureCategory.ai, Icons.smartphone, FeatureStatus.ready, 'aspect_ratio'),
    _f(89, 'ai_captions', 'AI Auto captions', 'AI Auto captions',
        FeatureCategory.ai, Icons.subtitles, FeatureStatus.ready, 'open_text'),
    _f(90, 'transcript_edit', 'بڕین لەسەر نووسین', 'Transcript-based edit',
        FeatureCategory.ai, Icons.text_snippet, FeatureStatus.ready, 'open_text'),
    _f(91, 'filler_remove', 'سڕینەوەی وشەی زیادە', 'Remove filler words',
        FeatureCategory.ai, Icons.backspace_outlined, FeatureStatus.ready, 'ai_soon'),
    _f(92, 'eye_contact', 'چاککردنی چاو', 'Eye-contact correction',
        FeatureCategory.ai, Icons.visibility, FeatureStatus.ready, 'ai_studio'),
    _f(93, 'ai_translate', 'وەرگێڕی ڤیدیۆ AI', 'AI Video Translator',
        FeatureCategory.ai, Icons.translate, FeatureStatus.ready, 'open_text'),
    _f(94, 'remove_bg', 'سڕینەوەی پاشبنەما', 'Remove background',
        FeatureCategory.ai, Icons.person_outline, FeatureStatus.ready, 'ai_studio'),
    _f(95, 'remove_object', 'سڕینەوەی ئۆبجێکت', 'AI Remove object',
        FeatureCategory.ai, Icons.auto_fix_off, FeatureStatus.ready, 'ai_studio'),
    _f(96, 'text_remover', 'سڕینەوەی نووسین لە ڤیدیۆ', 'AI Text Remover',
        FeatureCategory.ai, Icons.text_fields, FeatureStatus.ready, 'ai_studio'),
    _f(97, 'tts', 'دەنگی AI / TTS', 'Text-to-speech AI voice',
        FeatureCategory.ai, Icons.record_voice_over, FeatureStatus.ready, 'ai_studio'),
    _f(98, 'ai_avatar', 'AI Avatar', 'AI Avatar',
        FeatureCategory.ai, Icons.face_3, FeatureStatus.ready, 'ai_studio'),
    _f(99, 'lipsync', 'Lipsync', 'Lipsync',
        FeatureCategory.ai, Icons.mood, FeatureStatus.ready, 'ai_studio'),
    _f(100, 'mimic', 'Mimic Motion', 'Mimic Motion',
        FeatureCategory.ai, Icons.directions_run, FeatureStatus.ready, 'ai_studio'),
    _f(101, 'dialogue', 'AI Dialogue Scene', 'AI Dialogue Scene',
        FeatureCategory.ai, Icons.forum_outlined, FeatureStatus.ready, 'ai_studio'),
    _f(102, 'ai_image', 'دروستکردنی وێنەی AI', 'AI Image generate',
        FeatureCategory.ai, Icons.image_search, FeatureStatus.ready, 'ai_studio'),
    _f(103, 'ai_video', 'دروستکردنی ڤیدیۆی AI', 'AI Video generate',
        FeatureCategory.ai, Icons.videocam_outlined, FeatureStatus.ready, 'ai_studio'),
    _f(104, 'ai_music', 'دروستکردنی میوزیکی AI', 'AI Music generate',
        FeatureCategory.ai, Icons.queue_music, FeatureStatus.ready, 'ai_studio'),
    _f(105, 'text_to_video', 'Text-to-Video', 'Text-to-Video',
        FeatureCategory.ai, Icons.smart_display_outlined, FeatureStatus.ready,
        'ai_studio'),
    _f(106, 'story_maker', 'Story Maker', 'Story Maker',
        FeatureCategory.ai, Icons.auto_stories, FeatureStatus.ready, 'ai_studio'),
    _f(107, 'face_swap', 'Face swap', 'Face swap',
        FeatureCategory.ai, Icons.switch_account, FeatureStatus.ready, 'ai_studio'),
    _f(108, 'anime', 'Video to Anime', 'Video to Anime',
        FeatureCategory.ai, Icons.brush, FeatureStatus.ready, 'ai_studio'),
    _f(109, 'auto_styles', 'ستایلی ئۆتۆ AI', 'Auto Styles',
        FeatureCategory.ai, Icons.auto_awesome_motion, FeatureStatus.ready,
        'open_style'),
    _f(110, 'inpaint', 'Image inpainting', 'Image inpainting',
        FeatureCategory.ai, Icons.healing, FeatureStatus.ready, 'ai_studio'),
    _f(111, 'ai_character', 'AI Character', 'AI Character generator',
        FeatureCategory.ai, Icons.person_4_outlined, FeatureStatus.ready, 'ai_studio'),
    _f(112, 'beat_edit', 'مۆنتاژی بیت-ئاگاه', 'Beat-aware auto edit',
        FeatureCategory.ai, Icons.music_video, FeatureStatus.ready, 'effects'),
    _f(113, 'smart_template', 'پڕکردنەوەی تێمپلەیت', 'Smart template fill',
        FeatureCategory.ai, Icons.dashboard_customize, FeatureStatus.ready,
        'templates'),
    _f(114, 'prompt_edit', 'دەستکاری بە پرۆمپت', 'Prompt-based editing',
        FeatureCategory.ai, Icons.chat, FeatureStatus.ready, 'ai_studio'),
    _f(115, 'ai_credits', 'کریدیتی AI', 'Cloud AI credits',
        FeatureCategory.ai, Icons.stars_outlined, FeatureStatus.ready, 'open_export'),

    // G. Templates 116–125
    _f(116, 'template_cat', 'کتێبخانەی تێمپلەیت', 'Template catalog',
        FeatureCategory.templates, Icons.view_module, FeatureStatus.ready,
        'templates'),
    _f(117, 'trending', 'تێمپلەیتی ترێند', 'Trending TikTok templates',
        FeatureCategory.templates, Icons.trending_up, FeatureStatus.ready,
        'templates'),
    _f(118, 'one_tap', 'جێبەجێکردنی یەک-کرتە', 'One-tap template apply',
        FeatureCategory.templates, Icons.touch_app, FeatureStatus.ready,
        'open_style'),
    _f(119, 'brand_kits', 'Brand kits', 'Brand kits',
        FeatureCategory.templates, Icons.business, FeatureStatus.ready,
        'templates'),
    _f(120, 'stock', 'میدیای ستۆک', 'Stock media library',
        FeatureCategory.templates, Icons.photo_library_outlined, FeatureStatus.ready,
        'templates'),
    _f(121, 'share_social', 'هاوبەشکردن بۆ TikTok/Reels', 'Direct share social',
        FeatureCategory.templates, Icons.share, FeatureStatus.ready, 'open_export'),
    _f(122, 'cloud_sync', 'هاوکاتکردنی کلاود', 'Draft cloud sync',
        FeatureCategory.templates, Icons.cloud_sync, FeatureStatus.ready,
        'templates'),
    _f(123, 'collaborate', 'هاوکاری', 'Collaborate',
        FeatureCategory.templates, Icons.group_outlined, FeatureStatus.ready,
        'templates'),
    _f(124, 'backup', 'پاشەکەوتی پڕۆژە', 'Project backup',
        FeatureCategory.templates, Icons.backup, FeatureStatus.ready, 'backup'),
    _f(125, 'cross_device', 'درافتی فرە-ئامێر', 'Cross-device drafts',
        FeatureCategory.templates, Icons.devices, FeatureStatus.ready, 'backup'),

    // H. Export 126–135
    _f(126, 'export_1080', 'ئێکسپۆرت 720p / 1080p', 'Export 720p / 1080p',
        FeatureCategory.export, Icons.hd, FeatureStatus.ready, 'open_export'),
    _f(127, 'export_4k', 'ئێکسپۆرت 2K / 4K', 'Export 2K / 4K',
        FeatureCategory.export, Icons.four_k, FeatureStatus.ready, 'open_export'),
    _f(128, 'framerate', 'هەڵبژاردنی FPS', 'Frame rate options',
        FeatureCategory.export, Icons.timer_outlined, FeatureStatus.ready,
        'open_export'),
    _f(129, 'bitrate', 'Bitrate / quality', 'Bitrate / quality',
        FeatureCategory.export, Icons.high_quality, FeatureStatus.ready,
        'open_export'),
    _f(130, 'no_wm', 'بێ واتەرمارک', 'No watermark',
        FeatureCategory.export, Icons.verified, FeatureStatus.ready, 'open_export'),
    _f(131, 'export_gif', 'ئێکسپۆرتی GIF', 'Export GIF',
        FeatureCategory.export, Icons.gif, FeatureStatus.ready, 'open_export'),
    _f(132, 'batch_export', 'ئێکسپۆرتی کۆمەڵە', 'Batch export',
        FeatureCategory.export, Icons.playlist_add_check, FeatureStatus.ready,
        'open_export'),
    _f(133, 'hw_accel', 'Hardware acceleration', 'Hardware acceleration',
        FeatureCategory.export, Icons.memory, FeatureStatus.ready, 'open_export'),
    _f(134, 'proxy', 'Proxy / performance', 'Proxy / performance modes',
        FeatureCategory.export, Icons.speed, FeatureStatus.ready, 'ai_studio'),
    _f(135, 'project_presets', 'پڕیسێتی پڕۆژە', 'Project presets / ratios',
        FeatureCategory.export, Icons.settings_suggest, FeatureStatus.ready,
        'aspect_ratio'),

    // #136 — app specialty: full Kurdish AI subtitle studio
    _f(
      136,
      'kurdish_ai_subtitles',
      'ستۆدیۆی ژێرنووسی AI کوردی',
      'AI Kurdish Subtitles Studio',
      FeatureCategory.captions,
      Icons.subtitles_outlined,
      FeatureStatus.ready,
      'open_text',
    ),
  ];

  static AppFeature _f(
    int n,
    String id,
    String ku,
    String en,
    FeatureCategory cat,
    IconData icon,
    FeatureStatus status,
    String actionId,
  ) =>
      AppFeature(
        id: id,
        number: n,
        titleKu: ku,
        titleEn: en,
        category: cat,
        icon: icon,
        status: status,
        actionId: actionId,
      );
}
